### ISSUE TITLE
Add @Laryn as co-maintainer

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/easy_breadcrumb#16]
Per our Zulip exchange, I'll make a PR adding myself as a co-maintainer so I can merge some PRs and make a new release.

**Comment by laryn** [comment]
@jenlampton ☝️

**Comment by jenlampton** [comment]
Thank you @laryn !

**Comment by Greg-Boggs** [comment]
This is great! I will also try to help out here and there. I've enabled Github notifications, so I should get emailed now.
