### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by Wylbur** [backdrop-contrib/easy_breadcrumb#18]
I just installed this module, and I'm getting errors referenced in two issues #5 and #6.  It looks like this has been resolved, but there has not been a new release since 2019.  

Any chance we can get a new release with all the resolved issues included?

**Comment by laryn** [comment]
@Wylbur Yes, that was on my radar to do after verifying that Google is satisfied with recent changes: https://github.com/backdrop-contrib/easy_breadcrumb/issues/15

Unfortunately I haven't had a chance to come back and review that yet. But I think you're right, a new release is in order and if that other issue needs tweaking it can happen when it happens...

**Comment by laryn** [comment]
https://github.com/backdrop-contrib/easy_breadcrumb/releases/tag/1.x-2.17.1

**Comment by Wylbur** [comment]
Thanks so much for excellent responsiveness!  All set!
