### ISSUE TITLE
PHP error

### ISSUE THREAD

**Issue by deaddred** [backdrop-contrib/easy_breadcrumb#3]
BD 1.12.6 
PHP 7.2.18

Warning: Invalid argument supplied for foreach() in _easy_breadcrumb_check_excluded_path() (line 418 of /home/gtradjpd/public_html/modules/easy_breadcrumb-1.x-2.x/easy_breadcrumb.module).

**Comment by deaddred** [comment]
I'm guessing this has to do with Breadcrumb paths to be excluded not saving the settings.

**Comment by jenlampton** [comment]
I can confirm that this setting is not saving correctly, and I suspect that you are right that could be the cause of the PHP error.

**Comment by Wylbur** [comment]
Probably the same issue, but I am getting a different error message:

Warning: Invalid argument supplied for foreach() in _easy_breadcrumb_check_excluded_path() (line 444 of /home/lenaswan/lsbd/docroot/modules/contrib/easy_breadcrumb/easy_breadcrumb.module).

BD 1.17.4
easy_breadcrumb 1.x-2.17.0
PHP | Version: 7.2.26

**Comment by laryn** [comment]
I accidentally filed a duplicate issue and fixed this there:

 - https://github.com/backdrop-contrib/easy_breadcrumb/issues/9
