### ISSUE TITLE
Not working - Use the page title instead of the text from the URL. 

### ISSUE THREAD

**Issue by deaddred** [backdrop-contrib/easy_breadcrumb#4]
There's a setting "Use the page title (when available) instead of the text from the URL."  that when checked does not work. It still uses the URL to create the path name

Say you have two pages 
Named 
1) My Page The URL will be yoursite.com/my-page
2) My Page The URL will be yoursite.com/my-page-1

The module will only use the URL name to show in the bread crumbs. So for #2 instead of
Home > My Page it'll show Home > My Page 1

**Comment by jenlampton** [comment]
This setting is working for me now. Can you try it again with the latest version and let me know if you still have this problem?

**Comment by deaddred** [comment]
I'll test it later today.

**Comment by laryn** [comment]
PR available for testing here: https://github.com/backdrop-contrib/easy_breadcrumb/pull/12
